### ISSUE TITLE
HowToUse_SSL_LocalBlynkServer.md fine tuning

### ISSUE THREAD

**Issue by Zephael86** [khoih-prog/Blynk_WM#22]
Hello!

According to the guide "HowToUse_SSL_LocalBlynkServer.md" if local Blynk Server is used with OpenSSL certs, you have to edit either
~/Arduino/libraries/Blynk/src/certs/blynkcloud_der.h
or
~/Arduino/libraries/Blynk/src/certs/dst_der.h

I did this according to the instruction, but without luck.
ESP8266 was able to connect to Wifi, but no to Blynk.

Little background:
_I was stuck on ESP8266 version 2.4.2 because there was something changed with SSL with above versions.
Now I updated to version 2.7.1 and wanted to figure it out how is the connection done nowadays when SSL is used...
Blynk version: 0.6.1
Blynk_WifiManager: 1.0.16
OS: Windows 10_

When using sketch "Blynk_WM_Template" blynkcloud_der.h is read from
%USERPROFILE%\Documents\Arduino\libraries\ **Blynk_WiFiManager** \src\certs\
and not from
%USERPROFILE%\Documents\Arduino\libraries\ **Blynk** \src\certs\ as the guide suggests.

After editing the mentioned file, connection was ok!

I cannot test this on Linux.

**Comment by khoih-prog** [comment]
Thanks for using the [**Blynk_WM Library**](https://github.com/khoih-prog/Blynk_WM) and **not-updated** instructions in [**HowToUse_SSL_LocalBlynkServer**](https://github.com/khoih-prog/Blynk_WM/blob/master/extras/SSL_Notes/HowToUse_SSL_LocalBlynkServer.md).

I haven' touched it for a long time as I don't think anybody uses it. Thanks to your reminder, I'll have a look and update it.

Please use the updated instructions in [**Installation For Arduino IDE**](https://github.com/khoih-prog/Blynk_WM#i-for-arduino-ide)

> 4. COPY the `/certs` files from the main Blynk library to the Blynk_WiFiManager library.	
>    * **Find the `Blynk/src/certs` library directory.** (This is in the main Blynk library, may be named differently.)
>    * **Find the `Blynk_WiFiManager/src/certs` library directory.** (This is in the installed Blynk_WiFiManager library, may be named differently.) Using Arduino IDE, these directories are normally found under .../Arduino/Sketchbook/libraries or .../Arduino/libraries. 
>       * *(Sometimes Arduino IDE names a library folder with an unhelpful name like Arduino_12345. You can safely rename that folder under …/libraries/ to a compliant name like Blynk_WiFiManager for convenience. Remember to exit and restart IDE after renaming any library directory.)*
>    * **COPY (do not cut and paste) the entire contents** of the `Blynk/src/certs` directory to the `Blynk_WiFiManager/src/certs` directory.
>       * *(FYI: the reason for copying the certs from the Blynk library to Blynk_WiFiManager library is so that Blynk_WiFiManager will have access to Blynk's SSL certificates. And you almost certainly want to be using SSL!)*
>   * **You must do Step 4 each time you update the Blynk_WiFiManager library** to keep those SSL certs accessible. 

The reason for your issue is that the Arduino IDE will use the SSL certificates in  [**Blynk_WM Library**](https://github.com/khoih-prog/Blynk_WM) with higher priority than those in original [**Blynk Library**](https://github.com/blynkkk/blynk-library).
