### ISSUE TITLE
Exception 9: LoadStoreAlignmentCause: Load or store to an unaligned address

### ISSUE THREAD

**Issue by balucio** [khoih-prog/Blynk_WM#24]
Hi, I'm trying to use this useful library with "Dynamic Params". I defined the struct as reported at end, but when I try to Serial print the value value of `SENSOR_TYPE` (ex: `Serial.print("TIPO SENSORE ");Serial.println(SENSOR_TYPE);`) I get the exception as in subject.

Can you help me?
Thank you.

```c++
#define INFLUXDB_URL_LEN 251
char INFLUXDB_URL[INFLUXDB_URL_LEN + 1] = "http://influx.sapacasa.it:8086";

#define INFLUXDB_NAME_LEN 31
char INFLUXDB_NAME[INFLUXDB_NAME_LEN + 1] = "domus";

#define INFLUXDB_USER_LEN 31
char INFLUXDB_USER[INFLUXDB_USER_LEN + 1] = "usor";

#define INFLUXDB_PASS_LEN 31
char INFLUXDB_PASS[INFLUXDB_PASS_LEN + 1] = "usor";

#define SENSOR_NAME_LEN 31
char SENSOR_NAME[SENSOR_NAME_LEN + 1] = "SonOff";

#define SENSOR_TYPE_LEN 11
char SENSOR_TYPE[SENSOR_TYPE_LEN + 1] = "UNKNOW";

#define SENSOR_LOCATION_LEN 31
char SENSOR_LOCATION[SENSOR_LOCATION_LEN + 1] = "stanza letto";

#define SENSOR_BOOT_STATE_LEN 12
char SENSOR_BOOT_STATE[SENSOR_BOOT_STATE_LEN + 1]   = "ultimo";

MenuItem myMenuItems [] = {
  { "ixul", "Url InfluxDb",      INFLUXDB_URL,  INFLUXDB_URL_LEN  },
  { "ixdb", "Schema Influx",     INFLUXDB_NAME, INFLUXDB_NAME_LEN },
  { "ixun", "Utente Influx",     INFLUXDB_USER, INFLUXDB_USER_LEN },
  { "ixup", "Password Influx",   INFLUXDB_PASS, INFLUXDB_PASS_LEN },
  { "snnm", "Nome Sensore",      SENSOR_NAME,   SENSOR_NAME_LEN },
  { "sndv", "Tipo Sensore",      SENSOR_TYPE,   SENSOR_TYPE_LEN },
  { "ubic", "Ubicazione",        SENSOR_LOCATION, SENSOR_LOCATION_LEN },
  { "bste", "Stato iniziale",    SENSOR_BOOT_STATE, SENSOR_BOOT_STATE_LEN },
};

uint16_t NUM_MENU_ITEMS = sizeof(myMenuItems) / sizeof(MenuItem);  //MenuItemSize;
```

**Comment by khoih-prog** [comment]
Thanks for using the library and its powerful features.

The exception is possibly caused by something wrong in your code. Have a full check/review of the code, with the hints from this Google search [**Load or store to an unaligned address**](https://www.google.com/search?q=Load+or+store+to+an+unaligned+address&oq=Load+or+store+to+an+unaligned+address).

Many cases were caused by mistakes in the code, using delay() in wrong places, using EEPROM, etc.

1. [ESP Exception (9) and wdt reset when accessing a derived class through a base class pointer](https://github.com/esp8266/Arduino/issues/3365)

> You are instantiating an object on the stack, then saving the ptr in a global structure. You then go out of scope, so the stack object is destroyed, and the ptr you saved points to garbage.
> 
> The first version works only because you don't seem to make use of the stack object outside of its scope.
> 
> This is language usage error. There is much wrong with your design, including the use of C++ polymorphism. I suggest researching more about C++ polymorphism, object scope, and C++ OOP in general.
> 

2. [Exception 9 when using delay in both loop and callback](https://github.com/esp8266/Arduino/issues/5722)
3. [delay(1) in library sometimes causes exception(9)](https://github.com/esp8266/Arduino/issues/5838)

and many more...

**Try to simplify the code, step-by-step, to narrow down where the problem is. It;s also better to start from the working examples, then moving forward step-by-step.**

If you're using EEPROM, try to switch to better LittleFS, or at least SPIFFS.

Without the full code, nobody, even with the best crystal ball, can guess what's wrong. You can also post the issue to get help on Arduino/ESP forums as there are many experienced people there willing to help.

I'm sorry I can only help you by giving some hints and have no time to solve your problem, **unless you prove it's a bug of the examples or library.**

Good Luck,
